# Generated by Django 3.1.7 on 2021-04-17 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=250)),
                ('datetime', models.DateTimeField()),
                ('lastmodified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDB',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pick_address', models.CharField(max_length=250)),
                ('pick_pincode', models.IntegerField(validators=[django.core.validators.MinValueValidator(110001), django.core.validators.MaxValueValidator(110095)])),
                ('pick_phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('pick_note', models.CharField(blank=True, max_length=250)),
                ('pick_name', models.CharField(max_length=30)),
                ('delivery_address', models.CharField(max_length=250)),
                ('delivery_pincode', models.IntegerField(validators=[django.core.validators.MinValueValidator(110001), django.core.validators.MaxValueValidator(110096)])),
                ('delivery_phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('delivery_note', models.CharField(blank=True, max_length=250)),
                ('delivery_name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('cancelled', 'cancelled'), ('pending', 'pending'), ('accepted', 'accepted'), ('picked', 'picked'), ('completed', 'completed')], default='pending', max_length=20)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('cancelled_time', models.DateTimeField(null=True)),
                ('accepted_time', models.DateTimeField(null=True)),
                ('picked_time', models.DateTimeField(null=True)),
                ('completed_time', models.DateTimeField(null=True)),
                ('weight', models.IntegerField()),
                ('distance', models.IntegerField(null=True)),
                ('bill', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('pamyment_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
